spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: 'root'
    url: 'jdbc:postgresql://localhost:5432/SIF'
    password: 'root'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: 'update'
sif:
  config:
    mensagens:
      qtdmaiorquepermitida: 'Essa quantidade não pode ser adicionada, a quantidade
        maxima de selos para essa cartela é de #selos!'
      cartelacheia: 'Essa cartela já está cheia!'
      cartelaRepetida: 'O Usuário já possui esta cartela. Só pode ser adicionada novamente caso estiver completa!'
      cartelaRepetidaConvite: 'Você já possui esta cartela. Só pode ser adicionada novamente caso estiver completa!'
    cartela:
      serie: '00010000'
    modelo:
      convite:
        intervaloA: '100'
        intervaloB: '999'
        letrasAGerar: '2'
jwt:
  time: '86400000'
  salt: '1PMAUWooYBVioqLpmLhyu#1*3x(WYd8YwKE:Fwo0!71xVU@i.9Wf.XOSX6vtLl/ZSATjOy'
